// src/react/pages/About/index.js
import React from 'react';
import { connect } from 'react-redux';
import './index.scss';

class About extends React.Component {
    goVue () {
        window.location.href = '/vue/about';
    }
    changeRedux () {
        this.props.dispatch({
            type: 'aboutModel/save',
            payload: {
                name: '哈哈哈'
            }
        })
    }
    textSaga () {
        this.props.dispatch({
            type: 'aboutModel/textSaga',
            payload: {
                name: '我是saga在作怪'
            }
        })
    }
    render() {
        let { name } = this.props;
        return (
            <div className="about-class">
                <div className="icon"></div>
                <h3>组件About-react</h3>
                <div>redux测试name -- {name}</div>
                <div className="btn" onClick={() => this.changeRedux()}>
                    点击更新redux
                </div>
                <div className="btn" onClick={() => this.textSaga()}>
                    测试saga
                </div>
                <div className="btn" onClick={() => this.goVue()}>
                    点击跳转vue应用
                </div>
            </div>
        )
    }
}

function mapStateToProps(state) {
    return {
        ...state.aboutModel
    }
}
export default connect(mapStateToProps)(About);

// src/vue/pages/About/index.vue
<template>
    <div class="a-bout">
        <div class="icon" @click="changeName"></div>
        <div @click="changeActions">组件About-{{aboutData.name}}</div>
        <div @click="goReact" class="btn">点击跳转到react应用</div>
    </div>
</template>

<script>
import { mapState, mapMutations, mapActions } from 'vuex';

export default {
    data () {
        return {}
    },
    computed: mapState({
        aboutData: state => state.AboutStore
    }),
    methods: {
        changeName () {
            this.$store.commit({
                type: 'AboutStore/concat',
                payload: {
                    name: 'vue-new'
                }
            })
        },
        changeActions () {
            this.$store.dispatch({
                type: 'AboutStore/change',
                payload: {
                    name: 'vue-哈哈'
                }
            })
        },
        goReact () {
            window.location.href = '/react/about'
        }
    }
}
</script>

<style lang="scss">
    @import './index.scss';
</style>
